name: ActualShop
version: 1.0
description: A simple commandless shop plugin that uses an actual item for currency.
author: md_5
website: https://github.com/md-5/ActualShop

main: com.md5.actualshop.ActualShop
depend: [Deadbolt]

permissions:
#------------------------------------------------------------------------------#
    actualshop.*:
        description: All user and admin functionality - every possible node
        default: op
        children:
            actualshop.user.*: true
            actualshop.admin.*: true
#------------------------------------------------------------------------------#
    actualshop.user.*:
          description: All user functionality
          default: true
          children:
              actualshop.user.use: true
              actualshop.user.create: true        
#------------------------------------------------------------------------------#
    actualshop.admin.*:
      description: All admin functionality
      default: op
      children:
          actualshop.admin.destroy: true
          actualshop.admin.server: true
#------------------------------------------------------------------------------#